ci: add marker for all required status checks
https://brunoscheufler.com/blog/2022-04-09-the-required-github-status-check-that-wasnt

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -118,15 +118,36 @@ jobs:
             echo 'Found uncommitted changes' >&2
             exit 1
           fi
-  required_pre_merge_status_checks:
-    name: Status checks required before merge
-    if: github.event_name == 'pull_request'
+  required_pre_merge_status_checks_marker:
+    name: Status checks required before merge (marker)
     needs:
       - build_dev
       - build
       - test
       - generated_code_consistency
+    if: github.event_name == 'pull_request' && success()
     runs-on: ubuntu-latest
+    timeout-minutes: 1
     steps:
-      - name: ✅
-        run: echo "✅ The pull request passed required status checks."
+      - name: Mark all required status checks were successful
+        id: marker
+        run: echo "::set-output name=success::true"
+    outputs:
+      success: ${{ steps.marker.outputs.success }}
+  required_pre_merge_status_checks:
+    name: Status checks required before merge
+    needs: required_pre_merge_status_checks_marker
+    if: github.event_name == 'pull_request' && always()
+    runs-on: ubuntu-latest
+    timeout-minutes: 1
+    steps:
+      - name: Verify all required status checks passed
+        run: |
+          requirements_passed="${{ needs.required_pre_merge_status_checks_marker.outputs.success }}"
+          if [[ $requirements_passed == "true" ]]; then
+            echo "✅ The pull request passed all required status checks."
+            exit 0
+          else
+            echo "❗ Some of the required status checks failed or did not run."
+            exit 1
+          fi
